### ISSUE TITLE
Moderation not working

### ISSUE THREAD

**Issue by slyguy65** [jonas747/yagpdb#321] opened 2018-10-03 03:55 UTC
Trying to setup muting and kicking for certain roles, but it allows all of them, even when I restrict the use to certain roles...
I only got it to work when I went to the commands and made a custom override and restricting global use to the top role or two, and making an exception for everyone to let them use the "fun" things and making ANOTHER override for muting and unmuting. It makes no sense.

**Comment by jonas747** [comment] 2018-10-03 04:36
please provide more details on your setup

**Comment by jonas747** [comment] 2018-10-03 04:45
I just performed some tests and everything seems to be working as it should, it's likely you're misunderstanding something.

**Comment by buthed010203** [comment] 2018-10-03 11:51
Yeah it works perfectly fine hes just confused cause of channel overreides and command overrides in moderation section.

**Comment by slyguy65** [comment] 2018-10-03 23:09
Ok, well what can I do to fix this?
Is the positioning of mute role important? Or the bot? Because I try setting up the basic mute options "allow role"
I allow only role 1 and 2, THAT IS IT, but for some reason role 3 can mute people too. EVERYTHING else is basic, global settings are default and everything so what would the issue be.

**Comment by jonas747** [comment] 2018-10-04 00:31
reverting this would break so many server's setups, i can't.

I can however make a toggle for it.

**Comment by slyguy65** [comment] 2018-10-04 00:46
coolio

**Comment by evotodian** [comment] 2020-12-01 20:08
I have recently been outfitting a server with the yagpdb bot and have come across an issue. 

Everything was running smoothly until I enabled the moderation side of the bot. When someone was muted, I set it up to ignore all the roles except for the muted role. However, there was one role that made the bot freak out and glitch back and forth between the muted individual having said role and not having said role within seconds, even milliseconds of each other. The role in question is auto-assigned to members when they join the server. 

Is it something I did that caused this glitch to happen? If so how am I able to fix it?

**Comment by TheHDCrafter** [comment] 2020-12-01 20:13
> I have recently been outfitting a server with the yagpdb bot and have come across an issue. 
> 
> Everything was running smoothly until I enabled the moderation side of the bot. When someone was muted, I set it up to ignore all the roles except for the muted role. However, there was one role that made the bot freak out and glitch back and forth between the muted individual having said role and not having said role within seconds, even milliseconds of each other. The role in question is auto-assigned to members when they join the server. 
> 
> Is it something I did that caused this glitch to happen? If so how am I able to fix it?

We usually answer support questions on the [support server](https://discord.gg/nr9yyap). 
What could be the issue is autorole.
For example you are giving anyone the member role and removing it on mute.
What could also be the issue is the streaming announcement + mute

**Comment by buthed010203** [comment] 2020-12-02 14:48
Mm yes necroposts

**Closed** 2021-05-03 00:23 UTC
Labels: enhancement
